version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  api:
    build:
      context: ./api
      args:
        ENVIRONMENT: "dev"
    image: responder-api
    container_name: api
    environment:
      DB_HOST: mysql
      DB_USER: docker
      DB_PASSWORD: docker
      DB_DATABASE: test_db
    command: /bin/sh -c "python /app/hello.py"
    ports:
      - 80:80
